"""add pdf_url store

Revision ID: e9219c2506a8
Revises: 
Create Date: 2026-02-02 10:58:17.792003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9219c2506a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_receipts', sa.Column('business_store', sa.String(), nullable=True))
    op.add_column('order_receipts', sa.Column('pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_receipts', 'pdf_url')
    op.drop_column('order_receipts', 'business_store')
    # ### end Alembic commands ###
